# Generated by Django 3.0 on 2021-07-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название запроса')),
                ('hostname', models.CharField(max_length=100, null=True, verbose_name='Hostname')),
                ('days', models.IntegerField(null=True, verbose_name='Колличество дней')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ioc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Список IP')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('days', models.IntegerField(null=True, verbose_name='Колличество дней')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MacHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название запроса')),
                ('mac', models.CharField(max_length=15, null=True, verbose_name='MAC адрес')),
                ('days', models.IntegerField(null=True, verbose_name='Колличество дней')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Название запроса')),
                ('ip', models.CharField(max_length=15, null=True, verbose_name='IP адрес')),
                ('days', models.IntegerField(null=True, verbose_name='Колличество дней')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
